# -*- coding: utf-8 -*-
"""api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KffSQRxTqNKo9qzLEF5Y7TEPJytZHoYM

# Install package
"""

# !pip install requests

"""# Import library"""

import xml.etree.ElementTree as ET
import csv
import requests

response = requests.get(url='https://opendata.tycg.gov.tw/api/dataset/d7a0513d-1a91-4ae6-a06f-fbf83190ab2a/resource/8fa9af54-3048-4247-82eb-ad212464af65/download')
if response.ok:
    data = response.text
    root = ET.fromstring(data)

    routes = root.findall('Route')
    fieldnames = [elem.tag for elem in routes[0]]

    with open('api.csv', mode='w', newline='', encoding='utf-8') as ofs:
        writer = csv.DictWriter(ofs, fieldnames=fieldnames)
        writer.writeheader()

        for route in routes:
            row = {elem.tag: elem.text.strip() if elem.text else "" for elem in route}
            writer.writerow(row)
else:
    print(response.status_code)
